### ISSUE TITLE
outOfMemoryError proplem 

### ISSUE THREAD

**Issue by frankerang** [viirya/SparkAffinityPropagation#1]
I tried to run the  test example in AffinityPropagationSuite,  but I got this error
"uncaught error in thread SparkListenerBus, stopping SparkContext
java.lang.OutOfMemoryError: Java heap space"

The test data are just several pairs, why a OOM error happed?

I have checked the code, but did't where went wrong. something Wrong with Graphx?
BTW, I'm using spark 1.5.2, and run on Yarn

Thanks a lot

**Comment by johnwhumphreys** [comment]
Any update on this? Facing the same thing.

**Comment by viirya** [comment]
Can you tell more how do you run it? I can't reproduce it.

**Comment by viirya** [comment]
Btw, spark 1.5.2 seems too old version. I didn't test it.

**Comment by qiren007** [comment]
I got the same error on 3000 records. How many records it support?

**Comment by viirya** [comment]
It might be related how it computes `delta`.
