### ISSUE TITLE
Too many clusters

### ISSUE THREAD

**Issue by kikura3** [viirya/SparkAffinityPropagation#2]
We implemented our document clustering using scikit affinity propagation. To make it scalable, we rewritten it with your library. We observed that number of clusters were too many with spark version as opposed to the scikit version. Any thoughts?

**Comment by viirya** [comment]
Sorry for replying late.

If I remember it correctly, the cluster size (and number of clusters) in affinity propagation can be tuned by preferences. The recommended preferences is the paper is the median of similarities. I am not sure the preferences scikit affinity propagation uses.

Maybe you can use the `embedPreferences` API to manually set up preferences for tuning cluster size.
